* initial backup of a FS with multiple snapshots hung
if empty FS created manually or not existing
music-library conversion case, with old FS renamed
run zfs send/receive manually works
also had a hang with another backup
* test now fail because snapshots need to be mounted.
* allow for multiple limited to a particular backup set to allow for live backup
* allow for backup to different file system name so the individual base file system names don't cause confusion
* have ZFS subprocess errors raise ZfsError
* no reason for virtualDiskTests.py to be a class, except for config
* use pipettor instead of subprocess
* would like to remove "zfs-zipper" from "lib/zfs-zipper/zfszipper/", however this is
because of the way it is installed in /usr/local/lib
* less verbose dumps on errors by default, removing stack traces on certain exceptions
change:
logger.exception("zfs-zipper backup of failed")
* uses -R on send?
* make send/receive restartable
https://unix.stackexchange.com/questions/343675/zfs-on-linux-send-receive-resume-on-poor-bad-ssh-connection
use tiny FS to test failure.
don't need .tmp, the incomplete is there but need to either resume or abort with receive -A
* deal with syslog messages being too long
* Ideas to move files and snapshots from one pool to another
   https://docs.oracle.com/cd/E18752_01/html/819-5461/gbchx.html#gfwqb
* change log to get snap shot sizes from zfs list -t snap
* fix problem with auto import tests and mac virtual tests
  tests/virtualDiskTests.py
        # FIXME:  want to test auto-import, however if export test_backup, then import
        # with
        #   sudo zpool import -d /var/tmp/zfszipper_tests/dev/
        #   gets error: zfszipper_test_backup.dmg  UNAVAIL  cannot open

* initialize new zpool, which means creating parent file systems if they don't exist.

* mbuffer in pipe is suppose to really speed up zfs send/recieve

* syslog bufferr overflow
** running out of diskspace on backup media screws logging up:
    time	backupSet	backupPool	action	src1Snap	src2Snap	backupSnap	size	exception	info
    2019-02-19T20:13:23	osprey1	osprey_zackup1a	incr	a_pool/markd_a@zipper_2019-02-14T02:07:06_osprey1_incr	a_pool/markd_a@zipper_2019-02-19T20:13:09_osprey1_incr	osprey_zackup1a/a_pool/markd_a@zipper_2019-02-19T20:13:09_osprey1_incr	a_pool/markd_a@zipper_2019-02-19T20:13:09_osprey1_incr		
    2019-02-19T20:13:27	osprey1	osprey_zackup1a	incr	a_pool/osprey@zipper_2019-02-14T02:07:37_osprey1_incr	a_pool/osprey@zipper_2019-02-19T20:13:26_osprey1_incr	osprey_zackup1a/a_pool/osprey@zipper_2019-02-19T20:13:26_osprey1_incr	a_pool/osprey@zipper_2019-02-19T20:13:26_osprey1_incr		
    2019-02-19T20:13:32	osprey1	osprey_zackup1a	incr	a_pool/photo_a@zipper_2019-02-14T02:08:10_osprey1_incr	a_pool/photo_a@zipper_2019-02-19T20:13:30_osprey1_incr	osprey_zackup1a/a_pool/photo_a@zipper_2019-02-19T20:13:30_osprey1_incr	a_pool/photo_a@zipper_2019-02-19T20:13:30_osprey1_incr		
    2019-02-19T20:24:15	osprey1	osprey_zackup1a	error	b_pool/photo_b			Pipeline2Exception	zfs send -P -i b_pool/photo_b@zipper_2018-10-23T21:15:51_osprey1_incr b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr exited 1: incremental zipper_2018-10-23T21:15:51_osprey1_incr b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr 59726390344 size 59726390344 warning: cannot send 'b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr': signal received  zfs receive -F osprey_zackup1a/b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr exited 1: cannot receive incremental stream: out of space 	
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 877, in emit
        self.socket.send(msg)
    error: [Errno 40] Message too long
    Logged from file zfs-zipper, line 132
    .3error: zfs send -P -i b_pool/photo_b@zipper_2018-10-23T21:15:51_osprey1_incr b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr exited 1: incremental	zipper_2018-10-23T21:15:51_osprey1_incr	b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr	59726390344
    size	59726390344
    warning: cannot send 'b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr': signal received

    zfs receive -F osprey_zackup1a/b_pool/photo_b@zipper_2018-10-31T00:14:00_osprey1_incr exited 1: cannot receive incremental stream: out of space
     (specify --verboseLevel=error for more details)

** docs:
- syslog_ng https://gist.github.com/darconeous/1b3aee893536c1de2401
- dated, says UDP only, syslog_ng http://hints.macworld.com/article.php?story=20040710171559860
* Maybe switch to using one of the python ZFS APIs:
https://pypi.org/project/libzfs/
https://pypi.org/project/weir/
        
* want to test auto-import
however if export test_backup, then import with
  sudo zpool import -d /var/tmp/zfszipper_tests/dev/
  gets error: zfszipper_test_backupA.dmg  UNAVAIL  cannot open
   backupPool.exportPool()
* overwrite check is all wrong
** sendRecvFull allowOverwrite isn't coded correctly.
-F only rolls back, it doesn't start over.
testFullOverwrite and forceOverwrite not tested.  Maybe the whole allow overwrite needs to be re-thought tests are disabled
slog about on to long a message, temporaryly disable in confi
https://superuser.com/questions/168727/mac-extend-or-disable-500-messages-limit-of-console
* zfs library should return parsed results, rather than raw info
* BackupSnapshot FIXME: terminology is still confusing with much of the code used snapshotName rather than backupsetName
* figure out how to get unix domain sockets logging working
* figure out how to split up messages
* import update loggingOps from pycbo
